# Generated by Django 5.1.6 on 2025-03-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0004_categories_products_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
