# Generated by Django 5.1.6 on 2025-03-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0005_categories_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
    ]
