# Generated by Django 5.1.6 on 2025-03-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0007_categories_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='parent',
        ),
    ]
