# Generated by Django 5.1.6 on 2025-03-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0010_alter_products_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='slug',
            field=models.SlugField(default='Belirtilmemiş', unique=True),
        ),
    ]
