# Generated by Django 5.1.6 on 2025-03-17 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0011_subcategories_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltKategoriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='subcategory_images/')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Alt-Kategori',
                'verbose_name_plural': 'Alt-Kategoriler',
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='intern_app.categories'),
        ),
        migrations.DeleteModel(
            name='SubCategories',
        ),
    ]
