# Generated by Django 5.1.6 on 2025-03-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0012_altkategoriler_alter_products_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AltKategoriler',
        ),
        migrations.AddField(
            model_name='categories',
            name='sub_categories',
            field=models.ManyToManyField(to='intern_app.categories'),
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_category',
        ),
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.ManyToManyField(to='intern_app.categories'),
        ),
    ]
