# Generated by Django 5.1.6 on 2025-03-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0013_delete_altkategoriler_categories_sub_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, related_name='parent_categories', to='intern_app.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.ManyToManyField(related_name='products', to='intern_app.categories'),
        ),
    ]
