# Generated by Django 5.1.7 on 2025-03-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0014_alter_categories_sub_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.ManyToManyField(related_name='products', to='intern_app.categories', verbose_name='Ürün Kategorisi'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(null=True, verbose_name='Ürün Açıklaması'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to='products/', verbose_name='Ürün Görseli'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ürün Fiyatı'),
        ),
    ]
