# Generated by Django 5.1.7 on 2025-03-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0015_alter_products_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Kategori Açıklaması'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(upload_to='category_images/', verbose_name='Kategori Görseli'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Kategori İsmi'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Alan Adı'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, related_name='parent_categories', to='intern_app.categories', verbose_name='Alt Kategoriler'),
        ),
    ]
