# Generated by Django 5.1.7 on 2025-03-24 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0016_alter_categories_description_alter_categories_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern_app.products', verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Ürün Sayısı'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
