# Generated by Django 5.1.7 on 2025-03-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0017_alter_cartitem_cart_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Sepet', 'verbose_name_plural': 'Sepet'},
        ),
    ]
