# Generated by Django 5.1.7 on 2025-03-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0019_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Sepete Ürün', 'verbose_name_plural': 'Sepet'},
        ),
    ]
