# Generated by Django 5.1.7 on 2025-03-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0020_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personuser',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
    ]
