# Generated by Django 5.1.7 on 2025-04-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0021_alter_personuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_sub_cat',
            field=models.BooleanField(default=False, verbose_name='Alt Kategori mi?'),
        ),
    ]
