# Generated by Django 5.1.7 on 2025-04-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0022_categories_is_sub_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='is_sub_cat',
        ),
        migrations.AlterField(
            model_name='categories',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, related_name='parent_categories', to='intern_app.categories', verbose_name='Kategori Türü'),
        ),
    ]
