# Generated by Django 5.1.7 on 2025-04-04 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0023_remove_categories_is_sub_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='sub_categories',
        ),
        migrations.AddField(
            model_name='categories',
            name='sub_categories',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_categories', to='intern_app.categories', verbose_name='Üst Kategori'),
            preserve_default=False,
        ),
    ]
