# Generated by Django 5.1.7 on 2025-04-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0024_remove_categories_sub_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='sub_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_categories', to='intern_app.categories', verbose_name='Üst Kategori'),
        ),
    ]
