# Generated by Django 5.1.7 on 2025-04-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0026_remove_categories_sub_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, related_name='parent_categories', to='intern_app.categories', verbose_name='Alt Kategori olmasını istediğiniz kategorileri seçin:'),
        ),
    ]
