# Generated by Django 5.1.7 on 2025-04-04 13:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0027_alter_categories_sub_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Alan Adı'),
        ),
    ]
