# Generated by Django 5.1.7 on 2025-04-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0028_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, help_text='Birden fazla kategori seçmek için CTRL tuşuna basılı tutunuz.', related_name='parent_categories', to='intern_app.categories', verbose_name='Alt Kategori olmasını istediğiniz kategorileri seçin:'),
        ),
    ]
