# Generated by Django 5.1.7 on 2025-04-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0030_alter_categories_sub_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.ManyToManyField(help_text='Birden fazla kategori seçmek için CTRL tuşuna basılı tutunuz. \n Aynı zamanda seçimi iptal etmek için CTRL tuşuna basılı tutup seçimi iptal edilmek istenen kategoriye tıklayın.', related_name='products', to='intern_app.categories', verbose_name='Ürün Kategorisi'),
        ),
    ]
