# Generated by Django 5.1.7 on 2025-04-11 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0032_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='billing_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.CreateModel(
            name='BilledItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.IntegerField()),
                ('bills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern_app.billing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern_app.products')),
            ],
        ),
    ]
