# Generated by Django 5.1.7 on 2025-04-11 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0033_billing_billing_total_price_billeditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='billing_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Toplam Fiyat'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='card_cvv',
            field=models.CharField(max_length=3, verbose_name='Kart CVV'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='card_exp',
            field=models.CharField(max_length=5, verbose_name='Kart Son Kullanma Tarihi'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='card_no',
            field=models.CharField(max_length=16, verbose_name='Kart Numarası'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='card_owner',
            field=models.CharField(max_length=255, verbose_name='Kart Sahibi İsim-Soyisim'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='city',
            field=models.CharField(max_length=255, verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Zamanı'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='E-Posta'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='message',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='billing',
            name='name',
            field=models.CharField(max_length=255, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='pay_id',
            field=models.CharField(max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='billing',
            name='pay_method',
            field=models.CharField(max_length=255, verbose_name='Ödeme Yöntemi'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('Yola Çıktı', 'Yola Çıktı'), ('Tamamlandı', 'Tamamlandı')], default='Bekliyor', max_length=150, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Soyisim'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='telno',
            field=models.CharField(max_length=11, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='town',
            field=models.CharField(max_length=255, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='tracking_no',
            field=models.CharField(max_length=150, null=True, verbose_name='Takip No'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Zamanı'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='zipcode',
            field=models.CharField(max_length=5, verbose_name='Zip Kodu'),
        ),
    ]
