# Generated by Django 5.1.7 on 2025-04-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0034_alter_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='pay_id',
        ),
    ]
