# Generated by Django 5.1.7 on 2025-04-14 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0035_remove_billing_pay_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billeditems',
            options={'verbose_name': 'Faturalanmış Ürün', 'verbose_name_plural': 'Faturalanmış Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='billing',
            options={'verbose_name': 'Fatura', 'verbose_name_plural': 'Faturalar'},
        ),
        migrations.AddField(
            model_name='billeditems',
            name='no',
            field=models.CharField(max_length=150, null=True, verbose_name='Ürün Numarası'),
        ),
        migrations.AlterField(
            model_name='billeditems',
            name='bills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern_app.billing', verbose_name='Ürünün Ait Olduğu Fatura'),
        ),
        migrations.AlterField(
            model_name='billeditems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='billeditems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern_app.products', verbose_name='Ürün'),
        ),
        migrations.AlterField(
            model_name='billeditems',
            name='quantity',
            field=models.IntegerField(verbose_name='Adet'),
        ),
    ]
