# Generated by Django 5.1.7 on 2025-04-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0036_alter_billeditems_options_alter_billing_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
