# Generated by Django 5.1.7 on 2025-04-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0037_products_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resimler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim_isim', models.CharField(max_length=255, verbose_name='Resim Adı')),
                ('resim_gorseli', models.ImageField(upload_to='reklam_gorsel/', verbose_name='Görsel')),
            ],
        ),
    ]
