# Generated by Django 5.1.7 on 2025-04-28 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0038_resimler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resimler',
            options={'verbose_name': 'Resim', 'verbose_name_plural': 'Resimler'},
        ),
        migrations.CreateModel(
            name='CartItemQuickBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.PositiveIntegerField(default=1, verbose_name='Ürün Sayısı')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern_app.products', verbose_name='Ürün Adı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
