# Generated by Django 5.1.7 on 2025-04-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0039_alter_resimler_options_cartitemquickbuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemquickbuy',
            name='item_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Ürün Sayısı'),
        ),
    ]
