# Generated by Django 5.1.7 on 2025-04-29 11:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0040_alter_cartitemquickbuy_item_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_title', models.CharField(default='Varsayılan Adres', max_length=255)),
                ('name', models.CharField(max_length=255, verbose_name='İsim')),
                ('surname', models.CharField(max_length=255, verbose_name='Soyisim')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='E-Posta')),
                ('telno', models.CharField(max_length=11, verbose_name='Telefon Numarası')),
                ('city', models.CharField(max_length=255, verbose_name='İl')),
                ('town', models.CharField(max_length=255, verbose_name='İlçe')),
                ('zipcode', models.CharField(max_length=5, verbose_name='Zip Kodu')),
                ('open_address', models.CharField(max_length=300, verbose_name='Açık Adres')),
                ('isDefault', models.BooleanField(default=False)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern_app.billeditems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(default='Varsayılan Kart', max_length=255)),
                ('card_no', models.CharField(max_length=16, verbose_name='Kart Numarası')),
                ('card_exp', models.CharField(max_length=5, verbose_name='Kart Son Kullanma Tarihi')),
                ('card_owner', models.CharField(max_length=255, verbose_name='Kart Sahibi İsim-Soyisim')),
                ('card_cvv', models.CharField(max_length=3, verbose_name='Kart CVV')),
                ('isDefault', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
