# Generated by Django 5.1.7 on 2025-04-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0041_address_creditcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='fatura',
        ),
    ]
