# Generated by Django 5.1.7 on 2025-04-30 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0042_remove_address_fatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='telno',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^\\d{11}$')], verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='\\d{5}$')], verbose_name='Zip Kodu'),
        ),
    ]
