# Generated by Django 5.1.7 on 2025-04-30 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0043_alter_address_telno_alter_address_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_cvv',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='^\\d{3}$')], verbose_name='Kart CVV'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_no',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\d{16}$')], verbose_name='Kart Numarası'),
        ),
    ]
