# Generated by Django 5.1.7 on 2025-05-02 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0044_alter_creditcard_card_cvv_alter_creditcard_card_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_no',
            field=models.CharField(error_messages={'min_length': 'Minimum 16 hane girmeniz gerekli'}, max_length=16, validators=[django.core.validators.RegexValidator(message='Kart numarasi 16 haneli olmalıdır!', regex='^\\d{16}$')], verbose_name='Kart Numarası'),
        ),
    ]
