# Generated by Django 5.1.7 on 2025-05-02 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0045_alter_creditcard_card_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_cvv',
            field=models.CharField(error_messages={'min_length': 'CVV Minimum 3 haneli olmalıdır'}, max_length=3, validators=[django.core.validators.RegexValidator(message='CVV 3 haneli olmalıdır!', regex='^\\d{3}$')], verbose_name='Kart CVV'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_owner',
            field=models.CharField(error_messages={'min_length': 'İsim ve soyisminiz toplamda 4 haneden az olmamalıdır!'}, max_length=255, validators=[django.core.validators.RegexValidator(message='İsim ve soyisim giriniz.', regex='^\\w{5}$')], verbose_name='Kart Sahibi İsim-Soyisim'),
        ),
    ]
