# Generated by Django 5.1.7 on 2025-05-02 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0046_alter_creditcard_card_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_owner',
            field=models.CharField(error_messages={'min_length': 'İsim ve soyisminiz toplamda 4 haneden az olmamalıdır!'}, max_length=255, validators=[django.core.validators.RegexValidator(message='İsim ve soyisim giriniz.', regex='^([a-zA-ZçÇğĞıİöÖşŞüÜ]{2,70} ?){2,4}$')], verbose_name='Kart Sahibi İsim-Soyisim'),
        ),
    ]
