# Generated by Django 5.1.7 on 2025-05-12 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0047_alter_creditcard_card_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_owner',
            field=models.CharField(error_messages={'min_length': 'İsim ve soyisminiz toplamda 4 haneden az olmamalıdır!'}, max_length=255, validators=[django.core.validators.RegexValidator(message='İsim ve soyisminiz 2 ila 70 karakter arasında olmalı.', regex='^([a-zA-ZçÇğĞıİöÖşŞüÜ]{2,70} ?){2,4}$')], verbose_name='Kart Sahibi İsim-Soyisim'),
        ),
    ]
