# Generated by Django 5.1.7 on 2025-05-15 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_app', '0049_alter_creditcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adres_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
